# Generated by Django 4.2.2 on 2023-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
