# Generated by Django 4.2.2 on 2023-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_register_password_alter_register_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
