# Generated by Django 4.2.2 on 2023-07-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_applicationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
