# Generated by Django 4.2.2 on 2023-07-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_applicationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
